# Last-tested stack build plan using GHC 8

resolver: lts-7.19

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
# for hledger-ui:
- vty-5.15
- brick-0.17
- text-zipper-0.10
# for hledger-web:
- wai-handler-launch-3.0.2.2
- yesod-auth-1.4.16

# cf https://github.com/commercialhaskell/stack/wiki/stack.yaml
