# docs: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# this or a newer snapshot is suggested (hledger-api/servant/aeson requires > lts-5)
resolver: lts-5.16

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
- brick-0.6
- vty-5.5.0
- wai-handler-launch-3.0.2

#flags:

# ghc-options:
#   rtsopts:
#     all
