# docs: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# this or a newer snapshot is suggested (hledger-api/servant/aeson requires > lts-5)
resolver: nightly-2016-04-01

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api
- location:
    git: https://github.com/simonmichael/wai
    commit: 96847d4cfc5894823f591746cac32416f941ed90
  subdirs:
    - wai-handler-launch

extra-deps:
- file-embed-0.0.10

#flags:

# ghc-options:
#   rtsopts:
#     all
