# docs: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

#flags:

resolver: nightly-2015-11-04  # or newer

extra-deps:
- uglymemo-0.1.0.1

# ghc-options:
#   rtsopts:
#     all
