# cf https://github.com/commercialhaskell/stack/wiki/stack.yaml

resolver: nightly-2015-10-25  # or newer

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

flags:

extra-deps:
- uglymemo-0.1.0.1

# ghc-options:
#   rtsopts:
#     all
