# stack build plan using GHC 8.8.1

resolver: nightly-2019-12-24
# allow-newer: true

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

extra-deps:
# for hledger-lib:
# for hledger:
# for hledger-ui:
- brick-0.50.1
- vty-5.26
# for hledger-web:
