# Last-tested stack build plan using GHC 8.0.
# Older/newer snapshots in this series will likely work also.

resolver: lts-7.7

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
# for hledger-ui:
- brick-0.15
- vty-5.14
- text-zipper-0.8.1
# for hledger-web:
- wai-handler-launch-3.0.2.1

# cf https://github.com/commercialhaskell/stack/wiki/stack.yaml
