# stack build plan using GHC 8.2.x

resolver: lts-10.3

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
- easytest-0.1
