# stack build plan using GHC 8.8.3

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# stack seems to enable this by default now, basically disabling bounds checks. Force it off.
#allow-newer: false
#resolver: nightly-2020-01-31
resolver: lts-15.4

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
# for hledger-lib:
# for hledger:
# for hledger-ui:
# for hledger-web:
# for Shake.hs:

# for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# apply-ghc-options: everything
# rebuild-ghc-options: true
# stack build --profile --ghc-options="-fno-prof-auto"
