# stack build plan using GHC 9.8.1

resolver: nightly-2024-03-14

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

# XXX
extra-deps:
- base64-0.4.2.4            # hledger-web does not yet support base64-1
- cassava-megaparsec-2.1.1  # to support current bytestring/vector; not yet in stackage
- email-validate-2.3.2.20   # to support 9.8's template-haskell; not yet in stackage
- yesod-1.6.2.1             # not yet in stackage
- yesod-form-1.7.6          # not yet in stackage

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# ghc-options:
#   "$locals": -Wno-x-partial
#   "$locals": -fplugin Debug.Breakpoint

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
