# docs: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

#flags:

resolver: lts-4.2  # or newer

extra-deps:
- servant-swagger-0.1

# ghc-options:
#   rtsopts:
#     all
