# docs: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

#flags:

resolver: lts-4.1  # or newer

# extra-deps:

# ghc-options:
#   rtsopts:
#     all
