# stack build plan using GHC 8.4.1 and recent stackage nightly

resolver: nightly-2018-03-25

packages:
- hledger-lib
- hledger
# - hledger-ui  # blocked on hinotify's async bound
- hledger-web
- hledger-api

extra-deps:
# hledger-lib
- easytest-0.1.1
# hledger-ui
# - fsnotify-0.2.1.1
# hledger-web
- json-0.9.2
- wai-handler-launch-3.0.2.4
# hledger-api
- servant-server-0.13
- servant-swagger-1.1.5
- swagger2-2.2.1
- http-media-0.7.1.2
- servant-0.13

nix:
  pure: false
  packages: [perl gmp ncurses zlib]
