# stack build plan using GHC 8.4.2 and recent stackage nightly

resolver: nightly-2018-04-25

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
# try workaround for appveyor, https://github.com/yav/pretty-show/issues/27
- git: https://github.com/simonmichael/pretty-show.git
  commit: 225bcff3302f72cf739172f4e42792a7448eaa6c
# hledger-lib
- easytest-0.1.1
# hledger-ui
- fsnotify-0.2.1.2
# hledger-web
- json-0.9.2
- wai-handler-launch-3.0.2.4
# hledger-api
- servant-server-0.13
- servant-swagger-1.1.5
- swagger2-2.2.1
- http-media-0.7.1.2
- servant-0.13

nix:
  pure: false
  packages: [perl gmp ncurses zlib]
