# stack build plan using GHC 8.0.2 (osx sierra compatible)
# keep synced with download.md

resolver: lts-8.23

extra-deps: []

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api
