# stack build plan using GHC 8.4.3 and recent stackage nightly

resolver: nightly-2018-07-09

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
- cassava-megaparsec-2.0.0
- megaparsec-7.0.1
- config-ini-0.2.3.0

nix:
  pure: false
  packages: [perl gmp ncurses zlib]
