# Last-tested stack build plan using GHC 8.0.2 (osx sierra compatible)
# stack.yaml help: https://github.com/commercialhaskell/stack/wiki/stack.yaml

resolver: lts-8.2

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps: []
