# some older and newer lts-7 snapshots will also work here
resolver: lts-7.4

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api

extra-deps:
# for hledger-ui:
- brick-0.8
- text-zipper-0.4
- vty-5.7.1
# for hledger-web:
- wai-handler-launch-3.0.2.1

# cf https://github.com/commercialhaskell/stack/wiki/stack.yaml
