# stack build plan using GHC 8.0.2 (osx sierra compatible)
# keep synced with download.md

resolver: lts-9.0

extra-deps:
 []
#megaparsec >=6: 
#- megaparsec-6.0.0
#- parser-combinators-0.1.0

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api
