# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

blank_issues_enabled: true
contact_links:
  - name: hledger chat or mail list
    url: https://hledger.org/#help-feedback
    about: Please send questions and support requests here.
  - name: hledger project security issues
    url: mailto:simon@joyful.com
    about: Please report security vulnerabilities here.
