# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

blank_issues_enabled: true
contact_links:

  - name: A support request
    url: https://hledger.org/support.html
    about: For questions and support, please use our chat or mail list. See hledger.org > Support.

  - name: A security issue
    url: https://joyful.com
    about: Contact simon@joyful.com.
