# TRIGGER: Runs when triggered manually.
# ACTION: Uploads binaries from the latest successful binaries-* runs to the current "nightly" prerelease.
# Should not change anything else about the prerelease.

name: nightly

on:
  workflow_dispatch:
  # push:

jobs:
  publish-binaries:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    # Alternative:
    # just ghruns-download
    - name: Get artifact from latest successful binaries-windows-x64 run
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
        # https://github.com/dawidd6/action-download-artifact v3.1.4, unverified so needs to be whitelisted in repo settings
      with:
        workflow: binaries-windows-x64.yml
        # Optional, will use specified workflow run
        # use ${{ github.event.workflow_run.id }} when your action runs in a workflow_run event
        # and wants to download from the triggering workflow run
        # run_id: 1122334455
        # If no workflow is set and workflow_search set to true, then the most recent workflow matching
        # all other criteria will be looked up instead of using the current workflow
        workflow_search: false
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        # Use the empty string ("") to ignore status or conclusion in the search
        workflow_conclusion: success
        # Optional, will get head commit SHA
        # pr: ${{github.event.pull_request.number}}
        # Optional, no need to specify if PR is
        # commit: ${{github.event.pull_request.head.sha}}
        # Optional, will use the specified branch. Defaults to all branches
        # branch: binaries-linux-x64
        # Optional, defaults to all types
        # event: push
        # Optional, run number from the workflow
        # run_number: 34
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them into respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        # is treated as a regular expression if input name_is_regexp is true
        # will download only those artifacts with a name that matches this regular expression
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions
        # name: artifact_name
        # Optional, name is treated as a regular expression if set true
        # name_is_regexp: true
        # Optional, a directory where to extract artifact(s), defaults to the current directory
        path: artifacts
        # Optional, defaults to current repo
        # repo: ${{ github.repository }}
        # Optional, check the workflow run to whether it has an artifact
        # then will get the last available artifact from the previous workflow
        # default false, just try to download from the last one
        # check_artifacts: false
        # Optional, search for the last workflow run whose stored an artifact named as in `name` input
        # default false
        # search_artifacts: false
        # Optional, choose to skip unpacking the downloaded artifact(s)
        # default false
        # windows artifact is just zipped, no need to repack
        skip_unpack: true
        # Optional, choose how to exit the action if no artifact is found
        # can be one of:
        #  "fail", "warn", "ignore"
        # default fail
        # if_no_artifact_found: fail
        # Optional, allow forks when searching for artifacts
        # default true
        allow_forks: false

    - name: Get artifact from latest successful binaries-linux-x64 run
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
      with:
        workflow: binaries-linux-x64.yml
        allow_forks: false
        path: artifacts

    - name: Get artifact from latest successful binaries-mac-arm64 run
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
      with:
        workflow: binaries-mac-arm64.yml
        allow_forks: false
        path: artifacts

    - name: Get artifact from latest successful binaries-mac-x64 run
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
      with:
        workflow: binaries-mac-x64.yml
        allow_forks: false
        path: artifacts

    - name: Inspect artifacts
      shell: bash
      run: |
        ls -lRFh artifacts

    # The unix files were
    # 1. tarred to protect their executable permissions,
    # 2. mandatorily zipped by actions/upload-artifact,
    # 3. unzipped by dawidd6/action-download-artifact.
    # Now we 4. gzip them.
    - name: Gzip unix tarballs
      shell: bash
      run: |
        cd artifacts
        mv */*.tar .
        gzip *.tar

    - name: Inspect artifacts
      shell: bash
      run: |
        ls -lRFh artifacts

    # The nightly prerelease should already exist; this should only update its artifacts.
    # Alternative:
    # gh release upload {{ VER }} tmp/hledger-linux-x64.tar.gz
    # gh release upload {{ VER }} tmp/hledger-mac-arm64.tar.gz
    # gh release upload {{ VER }} tmp/hledger-mac-x64.tar.gz
    # gh release upload {{ VER }} tmp/hledger-windows-x64.zip
    - name: Upload artifacts to nightly prerelease
      uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87  # https://github.com/softprops/action-gh-release 2.0.5
      # permissions:
      #   contents: write
      with:
        tag_name: nightly      
        files: |
          artifacts/*.zip
          artifacts/*.tar.gz
        fail_on_unmatched_files: true
        prerelease: true
        # body_path: ghrelnotes-nightly.md
        #
        # https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing
        # body                     String   Text communicating notable changes in this release
        # body_path                String   Path to load text communicating notable changes in this release
        # draft                    Boolean  Indicator of whether or not this release is a draft
        # prerelease               Boolean  Indicator of whether or not is a prerelease
        # files                    String   Newline-delimited globs of paths to assets to upload for release
        # name                     String   Name of the release. defaults to tag name
        # tag_name                 String   Name of a tag. defaults to github.ref
        # fail_on_unmatched_files  Boolean  Indicator of whether to fail if any of the files globs match nothing
        # repository               String   Name of a target repository in <owner>/<repo> format. Defaults to GITHUB_REPOSITORY env variable
        # target_commitish         String   Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Defaults to repository default branch.
        # token                    String   Secret GitHub Personal Access Token. Defaults to ${{ github.token }}
        # discussion_category_name String   If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "Managing categories for discussions in your repository."
        # generate_release_notes   Boolean  Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes. See the GitHub docs for this feature for more information
        # append_body              Boolean  Append to existing body instead of overwriting it
        # make_latest              String   Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Can be true, false, or legacy. Uses GitHub api defaults if not provided
